### ISSUE TITLE
Updated the original script, would you mind reviewing it or testing it?

### ISSUE THREAD

**Issue by larrybolt** [colemickens/cloudflare-dyndns#3]
Hi!

Noticed your comment after a long time since I needed dynamic ip for cloudflare again, updated the script in the proces to list zones, record-id's and made it more modular (flags basically, lol)

https://gist.github.com/larrybolt/6295160

Would you mind giving it a quick review?

**Comment by colemickens** [comment]
Hi Larry! Thanks for the inspiration in that script. I just pulled it down and gave it a shot. Looks like it works fine to me. I liked the flag handling so I could just invoke it and it told me what I needed to add to get it running.

As for reviewing it, it looks good to me, but I try to avoid bash scripting as much as possible so I might not be the best judge.

Cheers.
